services:
  jenkins:
    build: jenkins-controller
    ports:
      - "8090:8080"
      - "5000:5000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/usr/local/configuration/jcac.yml
        #ssh-agent:
        #build: jenkins-agent
        #environment:
        #- JAVA_OPTS=-Djenkins.install.runSetupWizard=false
