credentials:
  system:
    domainCredentials:
    - credentials:
      - gitHubApp:
          appID: "896590"
          description: "Credentials for GitHub App"
          id: "github-app"
          privateKey: "${file:/usr/local/configuration/secrets/github-app.pem}"
      - basicSSHUserPrivateKey:
          description: "Credentials for VM Agent"
          id: "vm-agent"
          username: "jenkins"
          passphrase: "${SSH_VM_PASSWORD}"
          privateKeySource:
            directEntry:
              privateKey: "${file:/usr/local/configuration/secrets/vm_key}"

jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${USERNAME}"
          password: "${PASSWORD}"
  authorizationStrategy: "loggedInUsersCanDoAnything"
  numExecutors: 0
  clouds:
  - docker:
      containerCap: 20
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "unix:///var/run/docker.sock"
        readTimeout: 60
      name: "docker-cloud"
      templates:
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "marcelospe/kw-basic"
        labelString: "basic-agent"
        name: "Docker Agent"
        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "marcelospe/kw-kcov"
        labelString: "kcov-agent"
        name: "Kcov agent"
        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "marcelospe/kw-shellcheck"
        labelString: "shellcheck-agent"
        name: "Shellcheck agent"
        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
  nodes:
    - permanent:
        labelString: "vm-agent"
        name: "vm-agent"
        remoteFS: "/var/lib/jenkins"
        launcher: 
          ssh:
            credentialsId: vm-agent
            host: localhost
            port: VM_AGENT_PORT
            sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"

jobs:
  - file: /usr/local/configuration/jobs/jobs.groovy
