credentials:
  system:
    domainCredentials:
    - credentials:
      - gitHubApp:
          appID: "896590"
          description: "Credentials for GitHub App"
          id: "github-app"
          privateKey: "${file:/usr/local/configuration/secrets/github-app.pem}"
      - basicSSHUserPrivateKey:
          description: "Credentials for Docker SSH Agent"
          id: "docker-agent"
          username: "jenkins"
          passphrase: "${SSH_DOCKER_PASSWORD}"
          privateKeySource:
            directEntry:
              privateKey: "${file:/usr/local/configuration/secrets/container_key}"
      - basicSSHUserPrivateKey:
          description: "Credentials for VM Agent"
          id: "vm-agent"
          username: "jenkins"
          passphrase: "${SSH_VM_PASSWORD}"
          privateKeySource:
            directEntry:
              privateKey: "${file:/usr/local/configuration/secrets/vm_key}"

jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy: "loggedInUsersCanDoAnything"
  numExecutors: 0
  nodes:
    - permanent:
        labelString: "docker-agent"
        name: "docker-agent"
        remoteFS: "/home/jenkins/agent"
        launcher:
          ssh:
            credentialsId: docker-agent
            host: localhost
            port: DOCKER_AGENT_PORT
            sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"

jobs:
  - file: /usr/local/configuration/jobs/teste.groovy
